min
min

diff --git a/lw b/lw
--- a/lw
+++ b/lw
@@ -99,16 +99,15 @@ SHA256Hash() {
 }
 
 SetIAMAndRegion() {
-  # get variables from environment
+  # get credentials from environment variables
   if [ -z "${Region}" ] || [ -z "${AccessKeyId}" ] || [ -z "${SecretAccessKey}" ]; then
     if [ "${AWS_REGION}" ] && [ "${AWS_ACCESS_KEY_ID}" ] && [ "${AWS_SECRET_ACCESS_KEY}" ]; then
-      # get Region AccessKeyId SecretAccessKey from environment variables
       Region=${AWS_REGION}
       AccessKeyId=${AWS_ACCESS_KEY_ID}
       SecretAccessKey=${AWS_SECRET_ACCESS_KEY}
     fi
   fi
-  # get variables from ~/.aws/config and ~/.aws/credentials file
+  # get credentials from `~/.aws/config` and `~/.aws/credentials`
   if [ -z "${Region}" ] || [ -z "${AccessKeyId}" ] || [ -z "${SecretAccessKey}" ]; then
     if [ -r ~/.aws/credentials ]; then
       ini_region="" ini_aws_access_key_id="" ini_aws_secret_access_key=""
@@ -125,15 +124,14 @@ SetIAMAndRegion() {
       fi
     fi
   fi
-  # get variables from Instance Profile
+  # get credentials from Instance Profile
   if [ -z "${Region}" ] || [ -z "${AccessKeyId}" ] || [ -z "${SecretAccessKey}" ]; then
-    # get Region AccessKeyId SecretAccessKey from IAM Role and Instance Profile
-    Region=$(curl -sS --max-time 1 "http://169.254.169.254/latest/meta-data/placement/availability-zone" 2>/dev/null | sed 's/.$//' || true)
+    Region=$(curl -sS --max-time 1 http://169.254.169.254/latest/meta-data/placement/availability-zone 2>/dev/null | sed 's/.$//' || true)
     InstanceProfile=$(curl -sS --max-time 1 http://169.254.169.254/latest/meta-data/iam/security-credentials/ 2>/dev/null || true)
     IAMJSON=$(curl -sS --max-time 1 "http://169.254.169.254/latest/meta-data/iam/security-credentials/${InstanceProfile}" 2>/dev/null || true)
-    AccessKeyId=$(    echo "${IAMJSON}" | grep "AccessKeyId"     | sed 's/.*"[^"]*" : "\([^"]*\)".*/\1/g')
+    AccessKeyId=$(echo "${IAMJSON}" | grep "AccessKeyId" | sed 's/.*"[^"]*" : "\([^"]*\)".*/\1/g')
     SecretAccessKey=$(echo "${IAMJSON}" | grep "SecretAccessKey" | sed 's/.*"[^"]*" : "\([^"]*\)".*/\1/g')
-    STSToken=$(       echo "${IAMJSON}" | grep "Token"           | sed 's/.*"[^"]*" : "\([^"]*\)".*/\1/g')
+    STSToken=$(echo "${IAMJSON}" | grep "Token" | sed 's/.*"[^"]*" : "\([^"]*\)".*/\1/g')
 
     # if STSToken is null, regarding as not running on EC2.
     if [ -z "${STSToken}" ]; then
@@ -194,18 +192,17 @@ CanonicalHeader() {
 }
 
 CanonicalRequest() {
-  # ** blank lines are required **
   printf "%s\n" "${HTTPMethod}" # GET
   printf "%s\n" "${BucketPath}" # /your-backet
-  printf "%s\n" "${CanonicalQueryString}" # ?list-type=2&prefix=%2Fpath%2Fto%2Ffile
+  printf "%s\n" "$(echo "${CanonicalQueryString}" | sed 's/^?//')" # ?list-type=2&prefix=%2Fpath%2Fto%2Ffile
   printf "%s\n" "$(CanonicalHeader)"
-  printf "%s\n" ""
+  printf "%s\n" "" # blank lines are required
   printf "%s\n" "$(CanonicalHeader | sed 's/:.*/;/g' | while read -r LINE; do printf "%s" "${LINE}"; done | sed 's/;$//')"
   printf "%s\n" "${HashedPayload}"
 }
 
 SetAWSSignatureV4ForS3Get() {
-  # generate AWS Signature Version 4 for Amazon S3 REST API
+  # AWS Signature Version 4 for Amazon S3 REST API
   HTTPMethod="GET"
   APIEndpoint=$([ "${Region}" = us-east-1 ] && echo "s3.amazonaws.com" || echo "s3-${Region}.amazonaws.com")
   DateYMD=$(date +'%Y%m%d')
@@ -230,16 +227,15 @@ SetAWSSignatureV4ForS3Get() {
 }
 
 CallAPIS3Get() {
-  # run Amazon S3 REST API
   if [ "${STSToken}" ]; then
-    curl -LsS "https://${APIEndpoint}${BucketPath}$(if [ "${CanonicalQueryString}" ]; then printf "%s" "?${CanonicalQueryString}"; fi)" \
+    curl -LsS "https://${APIEndpoint}${BucketPath}${CanonicalQueryString}" \
       -H "Host: ${APIEndpoint}" \
       -H "x-amz-content-sha256: ${HashedPayload}" \
       -H "x-amz-date: ${DateISO8601}" \
       -H "x-amz-security-token: ${STSToken}" \
       -H "Authorization: ${Authorization}"
   else
-    curl -LsS "https://${APIEndpoint}${BucketPath}$(if [ "${CanonicalQueryString}" ]; then printf "%s" "?${CanonicalQueryString}"; fi)" \
+    curl -LsS "https://${APIEndpoint}${BucketPath}${CanonicalQueryString}" \
       -H "Host: ${APIEndpoint}" \
       -H "x-amz-content-sha256: ${HashedPayload}" \
       -H "x-amz-date: ${DateISO8601}" \
@@ -268,9 +264,9 @@ List() {
       # If there is an argument, list the objects.
       SetIAMAndRegion
       BucketPath="/$(ExtractHost "$1")"
-      CanonicalQueryString="list-type=2"
+      CanonicalQueryString="?list-type=2"
       if [ "${NextContinuationToken}" ]; then
-        CanonicalQueryString="continuation-token=${NextContinuationToken}&${CanonicalQueryString}"
+        CanonicalQueryString="${CanonicalQueryString}&continuation-token=${NextContinuationToken}"
       fi
       Prefix=$(UriEncode "$(ExtractPath "$1" | sed 's|^/||')")
       if [ "${Prefix}" ]; then
@@ -303,7 +299,6 @@ Get() {
 }
 
 S3() {
-  # check arguments num
   [ "$#" = 0 ] && Help && exit 1
   # check sub commands
   case $1 in
@@ -320,7 +315,6 @@ S3() {
 }
 
 main() {
-  # check arguments num
   [ "$#" = 0 ] && Help && exit 1
   # check sub commands
   case $1 in
