min

diff --git a/lw b/lw
--- a/lw
+++ b/lw
@@ -247,11 +247,11 @@ List() {
       CanonicalQueryString=""
       Payload=""
       SetAWSSignatureV4ForS3Get
-      APIResponse=$(CallAPIS3Get)
-      if echo "${APIResponse}" | grep -q "<Error>"; then
-        echo "${APIResponse}" && exit 1
+      Response=$(CallAPIS3Get)
+      if echo "${Response}" | grep -q "<Error>"; then
+        echo "${Response}" && exit 1
       else
-        echo "${APIResponse}" | grep -Eo "[^>]*</Name><CreationDate>[^<]*" | sed 's|\([^>]*\)</Name><CreationDate>\([^<]*\)|\2 \1|g;'
+        echo "${Response}" | grep -Eo "[^>]*</Name><CreationDate>[^<]*" | sed 's|\([^>]*\)</Name><CreationDate>\([^<]*\)|\2 \1|g;'
       fi
       ;;
     *)
@@ -259,19 +259,21 @@ List() {
       SetIAMAndRegion
       BucketPath="/$(ExtractHost "$1")"
       if [ -z "${MaxKeys}" ] || echo "${MaxKeys}" | grep -q '[^0-9]'; then MaxKeys=1000; fi
-      CanonicalQueryString="list-type=2&max-keys=${MaxKeys}"
-      if [ "${ContinuationToken}" ]; then CanonicalQueryString="continuation-token=${ContinuationToken}&${CanonicalQueryString}"; fi
       Prefix=$(UriEncode "$(ExtractPath "$1" | sed 's|^/||')")
-      if [ "${Prefix}" ]; then CanonicalQueryString="${CanonicalQueryString}&prefix=${Prefix}"; fi
+      CanonicalQueryString="$(
+        if [ "${ContinuationToken}" ]; then printf "%s" "continuation-token=${ContinuationToken}&"; fi
+      )list-type=2&max-keys=${MaxKeys}$(
+        if [ "${Prefix}" ]; then printf "%s" "&prefix=${Prefix}"; fi
+      )"
       Payload=""
       SetAWSSignatureV4ForS3Get
-      APIResponse=$(CallAPIS3Get)
-      if echo "${APIResponse}" | grep -q "<Error>"; then
-        echo "${APIResponse}" && exit 1
+      Response=$(CallAPIS3Get)
+      if echo "${Response}" | grep -q "<Error>"; then
+        echo "${Response}" && exit 1
       else
-        echo "${APIResponse}" | grep -Eo "[^>]*</Key><LastModified>[^<]*" | sed 's|\([^>]*\)</Key><LastModified>\([^<]*\)|\2 \1|g;'
-        if echo "${APIResponse}" | grep -Eq "<NextContinuationToken>[^<]*"; then
-          ContinuationToken=$(UriEncode "$(echo "${APIResponse}" | grep -Eo "<NextContinuationToken>[^<]*" | sed 's|.*>||g')")
+        echo "${Response}" | grep -Eo "[^>]*</Key><LastModified>[^<]*" | sed 's|\([^>]*\)</Key><LastModified>\([^<]*\)|\2 \1|g;'
+        if echo "${Response}" | grep -Eq "<NextContinuationToken>[^<]*"; then
+          ContinuationToken=$(UriEncode "$(echo "${Response}" | grep -Eo "<NextContinuationToken>[^<]*" | sed 's|.*>||g')")
           List "$@"
         fi
       fi
